[package]
name = "ad-icon-button-filled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
customelement = { version = "0.1.0", path = "../base/" }
wasm-bindgen = "0.2"
handlebars = "4.0"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Event",
    "Document",
    "HtmlElement",
    "Node",
    "Text",
    "HtmlButtonElement",
    "HtmlTemplateElement",
    "console"
]